### ISSUE TITLE
Keyboard detected only when powered through USB

### ISSUE THREAD

**Issue by jacereda** [rsta2/uspi#16]
Hi,

I'm trying the keyboard sample on a Raspberry PI 1 Model B. 

Everything is fine when I power the device through the USB port. The keyboard is properly detected and working.

But when I use the real thing (DC connector) it doesn't show in the enumerated devices, looks like it only detects the root.

I guess it could be related to the USB ports being configured as OTG or something like that, but I don't know how to fix it.

Maybe you could you point me in the right direction?

Thanks!

**Comment by rsta2** [comment]
There may be a problem with self-powered USB hubs in USPi. I have never tested it with self-powered hubs by myself, because I didn't have one. I have ordered a self-powered USB hub now and I hope I can reproduce and fix the problem with it. This will take some days.

**Comment by jacereda** [comment]
I'm not sure I explained the problem correctly.

This is the working configuration. The USB on the left is a direct cable to the keyboard. The cable on the right goes to an iPhone charger. Under normal circumstances, I can't power the device through USB. It seems to work at first but has problems later on when booting something like Linux. Seems to work with your samples though:

![working_hw](https://user-images.githubusercontent.com/4195919/44795351-c4d6c680-abaa-11e8-9352-cd4d4e8c7865.JPG)
![working_log](https://user-images.githubusercontent.com/4195919/44795354-c4d6c680-abaa-11e8-9dce-0cba98c615a1.JPG)

And this one fails, this is the normal way to power a Model B AFAIK.

![failing_hw](https://user-images.githubusercontent.com/4195919/44795505-2303a980-abab-11e8-9cd1-2c33bca2d939.JPG)
![failing_log](https://user-images.githubusercontent.com/4195919/44795506-2303a980-abab-11e8-9229-a32390f88e69.JPG)

I'm sorry to hear I made you buy one of those hubs, I'm afraid that's not my case. I'm willing to pay for it if you want.

**Comment by rsta2** [comment]
It seems I understood you wrong. USPi does not support OTG. Normally you cannot power the Raspberry Pi via a USB device connector. You have to connect a power supply to the dedicated power connector of the Raspberry Pi in any case. As I understand your second comment, this is the configuration which is working and it is all you can get from USPi. Don't worry because of the ordered USB hub. It's cheap and maybe I can use it otherwise.

**Comment by jacereda** [comment]
The funny thing is that the working configuration is powered via USB. If I connect a power supply via the DC connector I get the "Keyboard not found" message.

**Comment by rsta2** [comment]
This is really weird. From the pictures above, I thought it would be opposite behaviour. Unfortunately I have currently no explanation on this. I will try the USPi keyboard sample on my RPi 1 B with the most recent firmware again soon, to see if there is a firmware issue. Please note that it is AFAIK not common to power the RPi 1 B via the USB device ports. Because the RPi 1 B has an on-board USB hub connected to the USB root port, it can't be used in USB OTG device mode (like the RPi Zero).

**Comment by rsta2** [comment]
I have tested the USPi keyboard sample with the firmware from Aug-29 on an RPi 1 B with two different power supplies and two different keyboards. Everything is working well.

**Comment by jacereda** [comment]
Do you have anything in config.txt?

I'll buy another power supply, maybe there's some problem with mine...

**Comment by jacereda** [comment]
Damn it, I've been checking the documentation and what I thought was the DC in connector is an audio port. It's funny that it boots when powering the audio port...

And the worst part is that this is not the first time I get it wrong. 

So, forget the issue completely, the Model B must be powered through the micro-usb port. I'm sorry I wasted your time.
