### ISSUE TITLE
USPiInitialize hangs waiting for IRQ no. 9 never firing. PI3 B+

### ISSUE THREAD

**Issue by tetofonta** [rsta2/uspi#22]
Hi, I'm experiencing some problems implementing USPi as a usb driver for a bare metal project.
Once I setup the environment (everything except for timer routines) and the IRQ/FIQ handler works fine (because I've tested it with a system timer IRQ), calling USPiInitialize hangs in a while at line 719 of dwhcidevice.c =( never calling my IRQ handler.

**Comment by rsta2** [comment]
I have successfully tested the USPi keyboard sample with the latest firmware from [here](https://github.com/raspberrypi/firmware/tree/master/boot) again. I only had to remove the `-mfloat-abi=hard` option from the `ARCH ?=` line in Rules.mk, because the newer toolchain does not want it without specifying a `-mfpu=` option.

If I understand you right, you do not have the Timer routines in *include/uspios.h* implemented? If so, USPi cannot work, because it needs these routines.
