### ISSUE TITLE
Malloc should be 16-bytes aligned

### ISSUE THREAD

**Issue by tobast** [rsta2/uspi#8]
Hello,
In uspios.h, it is stated that malloc should return a "4-bytes aligned pointer", yet your environment aligns it to 16 bytes. USPiInitialize seems to hang forever if malloc aligns its result to 4-bytes only, and not to 16-bytes.
Am I doing something wrong, or is the documentation broken?

**Comment by rsta2** [comment]
There's a difference between the malloc() alignment requirements of the USPi library itself and the USPi Environment. The USPi library should work with 4-byte alignment and that's why it is noted in uspios.h that way. The environment needs 16-byte alignment (e.g. for the frame buffer info structure). That's why the malloc() in the environment always returns a 16-byte aligned memory block.
